#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftWheel,     tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     RightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FlagSwag,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Arminator,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{

	int limit = 5;
	while(true)
{

getJoystickSettings(joystick);
if(abs(joystick.joy1_y1) > limit && abs(joystick.joy1_y2) > limit){
motor[LeftWheel] = joystick.joy1_y1;
motor[RightWheel] = joystick.joy1_y2;
}
else{
motor[LeftWheel] = 0;
motor[RightWheel] = 0;
}
{
if(joystick.joy1_TopHat == 6){
motor[FlagSwag] = 100;
}
else{
motor[FlagSwag] = 0;
}
{
if(abs(joystick.joy2_y1) > limit){
motor[Arminator] = joystick.joy2_y1;
}
else{
motor[Arminator] = 0;
}
{

if(joystick.joy2_TopHat == 0){
servo(Wrist) = 45;
}

if(joystick.joy2_TopHat == 4){
servo(Wrist) = 180;
}

}
}
}
}
}
