#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     RightWheel,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     LeftWheel,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{

waitForStart();
motor[RightWheel] = 100;
motor[LeftWheel] = 100;
wait1Msec(2050);

motor[RightWheel] = 100;
motor[LeftWheel] = -100;
wait1Msec(430);

motor[RightWheel] = 100;
motor[LeftWheel] = 100;
wait1Msec(2000);

}
